const classChanges = [
  { time: 31, target: ".spellwidth35.al.ml", add: "textglow"},
  { time: 40, target: ".tpglowimage", add: "bglowimage" },
  { time: 52, target: ".astralhighlight", add:"newastralhighlight"},
  { time: 62, target: ".tpglowimage", remove: "bglowimage" },
  { time: 62, target: ".spellwidth35.al.ml", remove: "textglow"},
  { time: 62, target: ".al.bml.dissolvingmaintext.spt.width85", add: "ho" },
  { time: 91, target: ".al.bml.dissolvingmaintext.spt.width85", add: "biglineheight" },
  { time: 91, target: ".al.bml.dissolvingmaintext.spt.width85", remove: "ho" },
  { time: 105, target: ".titleescape.bml.italic.al", add: "newtitleescape" },
  { time: 105, target: ".titleescape.bml.italic.ar.bmr.pbss", add: "newtitleescape" },
  { time: 105, target: ".page", add: "pagenew1" },
  { time: 131, target: ".page", remove: "pagenew1" },
  { time: 140, target: ".juxtaposehighlight", add:"newjuxtaposehighlight"},
  { time: 159, target: ".techgnosticwidth35.al.ml", add: "textglow"},
  { time: 169, target: ".marshallglowimage", add: "bglowimage"},
  { time: 183, target: ".techgnosticwidth35.al.ml", remove: "textglow"},
  { time: 183, target: ".marshallglowimage", remove: "bglowimage"},
  { time: 193, target: ".page", add: "pagenew2" },
  { time: 200, target: ".page", remove: "pagenew2" },
  { time: 221, target: ".titleenigmatic.bml.italic.al.pbss", add: "newtitleenigmatic" },
  { time: 221, target: ".titleenigmatic.bml.italic.ar.bmr.pbss", add: "newtitleenigmatic" },
  { time: 239, target: ".fantasywidth50", add: "textglow"},
  { time: 240, target: ".fantasywidth50", add: "doubletextglow"},
  { time: 250, target: ".enlightenhighlight", add:"newenlightenhighlight"},
  { time: 268, target: ".daylitwidth35", add:"textglow"},
  { time: 268, target: ".spaceglowimage", add: "bglowimage"},
  { time: 293, target: ".trumpglowimage", add: "bglowimage"},
  { time: 282, target: ".daylitwidth35", remove:"textglow"},
  { time: 282, target: ".spaceglowimage", remove: "bglowimage"},
  { time: 301, target: ".trumpglowimage", remove: "bglowimage"},
  { time: 303, target: ".page", add: "pagenew4"},
  { time: 325, target: ".page", remove: "pagenew4"},
  { time: 311, target: ".titleweirdness.bml.italic.al.pbss", add: "newtitleweirdness" },
  { time: 311, target: ".titleweirdness.bml.italic.ar.bmr.pbss", add: "newtitleweirdness" },
  { time: 325, target: ".titleweirdness.bml.italic.al.pbss", remove: "newtitleweirdness" },
  { time: 325, target: ".titleweirdness.bml.italic.ar.bmr.pbss", remove: "newtitleweirdness" },
  { time: 329, target: ".algorithmhighlight", add:"newalgorithmhighlight"},
  { time: 340, target: ".dronewidth35", add:"textglow"},
  { time: 355, target: ".droneglowimage", add: "bglowimage"},
  { time: 369, target: ".droneglowimage", remove: "bglowimage"},
  { time: 369, target: ".dronewidth35", remove:"textglow"},
  { time: 393, target: ".erikglowimage", add: "bglowimage"},

];
